// Regenerates the TypeScript protobuf bindings in src/sim/proto/ from the .proto sources
// vendored at vendor/tbc-sim/proto/. Mirrors tbc-new's own `make proto` target
// (see vendor/tbc-sim/makefile:73-75), using @protobuf-ts/protoc's self-installed protoc
// binary so this doesn't depend on a system-wide protoc install.
//
// Output is gitignored (see src/sim/proto/.gitignore) and regenerated by this script,
// same as tbc-new does for its own ui/core/proto/.
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const protoDir = path.join(root, "vendor/tbc-sim/proto");
const outDir = path.join(root, "src/sim/proto");
fs.mkdirSync(outDir, { recursive: true });
const protocBin = path.join(root, "node_modules/.bin/protoc" + (process.platform === "win32" ? ".cmd" : ""));
const pluginBin = path.join(root, "node_modules/.bin/protoc-gen-ts" + (process.platform === "win32" ? ".cmd" : ""));

execFileSync(
	protocBin,
	[
		"--ts_opt",
		"generate_dependencies",
		"--ts_out",
		outDir,
		"--proto_path",
		protoDir,
		`--plugin=protoc-gen-ts=${pluginBin}`,
		path.join(protoDir, "api.proto"),
	],
	{ stdio: "inherit", shell: process.platform === "win32" },
);

console.log(`Generated protobuf-ts bindings into ${path.relative(root, outDir)}`);
